<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="csrf-token" content="<?= csrf_token(); ?>">

    <title><?= htmlspecialchars($pageTitle ?? 'Kr[HACK]ademy') ?></title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"/>
    <link rel="stylesheet" href="/css/style.css"/>
    <link rel="icon" type="image/png" href="/images/logo_krhacken_r.ico" />

    <?php if (!empty($specific_css)): ?>
        <?php foreach ($specific_css as $css_file): ?>
            <link rel="stylesheet" href="<?= htmlspecialchars($css_file) ?>">
        <?php endforeach; ?>
    <?php endif; ?>
</head>