<section class="search-panel" id="filter-controls" aria-hidden="true">
    <div class="search-header">
        <i class="fas fa-search panel-icon" aria-hidden="true"></i>
        <div class="input-wrapper">
            <input type="search" id="search-input" placeholder="Rechercher">
            <button id="clear-search-btn" class="fas fa-times" aria-label="Effacer la recherche"></button>
        </div>
        <div class="custom-select-wrapper">
            <div class="custom-select" data-select-id="category-filter">
                <span class="custom-select-trigger">Catégorie</span>
                <i class="fas fa-chevron-down"></i>
            </div>
            <div class="custom-options">
                <div class="custom-option" data-value="all">Toutes</div>
            </div>
            <input type="hidden" id="category-filter" name="category-filter" value="all">
        </div>
        <div class="custom-select-wrapper">
            <div class="custom-select" data-select-id="difficulty-filter">
                <span class="custom-select-trigger">Difficulté</span>
                <i class="fas fa-chevron-down"></i>
            </div>
            <div class="custom-options">
                <div class="custom-option" data-value="all">Toutes</div>
            </div>
            <input type="hidden" id="difficulty-filter" name="difficulty-filter" value="all">
        </div>
        <div class="custom-select-wrapper">
            <div class="custom-select" data-select-id="completion-filter">
                <span class="custom-select-trigger">Statut</span>
                <i class="fas fa-chevron-down"></i>
            </div>
            <div class="custom-options">
                <div class="custom-option" data-value="all">Tout</div>
                <div class="custom-option" data-value="completed">Complété</div>
                <div class="custom-option" data-value="not-completed">Non-complété</div>
            </div>
            <input type="hidden" id="completion-filter" name="completion-filter" value="all">
        </div>
        <button id="close-filter-btn" class="fas fa-times" aria-label="Fermer la barre de recherche"></button>
    </div>
</section>

<div class="no-results" id="no-results-message" style="display:none;">
    <p>Aucun résultat trouvé pour cette recherche.</p>
</div>

<script src="/js/search.js" defer></script>
<link rel="stylesheet" href="/css/widget.css"/>