<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Challenges - Kr[HACK]ademy</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"/>
    <link rel="stylesheet" href="/css/style.css"/>
    <link rel="stylesheet" href="/css/shared-components.css"/>
    <link rel="icon" type="image/png" href="/images/logo_krhacken_r.ico" />
</head>
<body>
    <?php require __DIR__ . '/partials/header.phtml'; ?>
    <main class="main">
        <?php
        $items = $challenges;
        $type = 'challenge';
        require __DIR__ . '/partials/content-grid.phtml';
        ?>
    </main>
    <?php require __DIR__ . '/partials/footer.phtml'; ?>
    <?php require __DIR__ . '/partials/modal.phtml';?>
</body>
</html>