<?php
$pageTitle = 'Scénarios - Kr[HACK]ademy';
$specific_css = ['/css/shared-components.css'];
?>
<!DOCTYPE html>
<html lang="fr">
<?php require __DIR__ . '/partials/head.phtml'; ?>
<body data-user-logged-in="<?= isset($_SESSION['user_id']) ? 'true' : 'false'; ?>">
    <?php require __DIR__ . '/partials/header.phtml'; ?>
    <main class="main">
        <h2 class="construction">page en construction</h2>
    </main>
    <?php require __DIR__ . '/partials/footer.phtml'; ?>
    <script src="/js/progress-tracker.js" defer></script>
    <?php require __DIR__ . '/partials/modal.phtml';?>
</body>
</html>